"""more collumns on food table

Revision ID: de3444f5b377
Revises: f971f67017ac
Create Date: 2021-08-20 14:01:44.989962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3444f5b377'
down_revision = 'f971f67017ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('fiber', sa.Float(), nullable=False))
    op.add_column('food', sa.Column('trans_fat', sa.Float(), nullable=False))
    op.add_column('food', sa.Column('monounsaturated_fat', sa.Float(), nullable=False))
    op.add_column('food', sa.Column('polyunsaturated_fat', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'polyunsaturated_fat')
    op.drop_column('food', 'monounsaturated_fat')
    op.drop_column('food', 'trans_fat')
    op.drop_column('food', 'fiber')
    # ### end Alembic commands ###
