"""added collision radius to foods table

Revision ID: f971f67017ac
Revises: 78cf10273288
Create Date: 2021-08-20 13:54:22.162123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f971f67017ac'
down_revision = '78cf10273288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('collision_radius', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'collision_radius')
    # ### end Alembic commands ###
